spring.application.name=traffic_simulator
traffic-simulator.enabled=${TRAFFIC_SIMULATOR_ENABLED:false}
traffic-simulator.events-per-tick=${TRAFFIC_SIMULATOR_EVENTS_PER_TICK:1}
traffic-simulator.tick-rate=${TRAFFIC_SIMULATOR_TICK_RATE:PT1S}
traffic-simulator.concurrent=${TRAFFIC_SIMULATOR_CONCURRENT:false}
traffic-simulator.send-retry-attempts=${TRAFFIC_SIMULATOR_SEND_RETRY_ATTEMPTS:3}
traffic-simulator.send-retry-backoff=${TRAFFIC_SIMULATOR_SEND_RETRY_BACKOFF:PT0.25S}

traffic-simulator.raw-events.exchange=${TRAFFIC_SIMULATOR_RAW_EVENTS_EXCHANGE:guardium.ingestion-events}
traffic-simulator.raw-events.routing-key=${TRAFFIC_SIMULATOR_RAW_EVENTS_ROUTING_KEY:ingestion-event.created}
