spring.application.name=traffic_simulator
traffic-simulator.enabled=${TRAFFIC_SIMULATOR_ENABLED:false}
traffic-simulator.ingestion-api-url=${INGESTION_API_URL:http://localhost:8080/events}
traffic-simulator.events-per-tick=${TRAFFIC_SIMULATOR_EVENTS_PER_TICK:1}
traffic-simulator.tick-rate=${TRAFFIC_SIMULATOR_TICK_RATE:PT1S}
