spring.application.name=ingestion_processor
spring.jpa.hibernate.ddl-auto=update
ingestion.events.exchange=${INGESTION_EVENTS_EXCHANGE:guardium.access-events}
ingestion.events.routing-key=${INGESTION_EVENTS_ROUTING_KEY:access-event.created}
